import type { AiModelId } from "@prisma/client";
import { normalizeEvaluationResult } from "./evaluationParse";
import { scoreToRating } from "@/lib/evaluation/rating";
import type {
  AiProvider,
  CompletionRequest,
  CompletionResult,
  EvaluationInput,
  EvaluationResult,
  OptimizeRequest,
  OptimizeResult,
} from "./types";

const MODEL_LABELS: Record<AiModelId, string> = {
  GPT: "GPT-4o (demo)",
  GEMINI: "Gemini 2.0 (demo)",
  CLAUDE: "Claude 3.5 (demo)",
};

function hashSeed(text: string): number {
  let h = 0;
  for (let i = 0; i < text.length; i++) h = (h * 31 + text.charCodeAt(i)) | 0;
  return Math.abs(h);
}

function mockLatency(text: string): number {
  return 400 + (hashSeed(text) % 900);
}

function mockTokens(text: string): { input: number; output: number } {
  const input = Math.max(12, Math.ceil(text.length / 4));
  const output = 120 + (hashSeed(text) % 180);
  return { input, output };
}

function buildMockCompletion(prompt: string, category: string): string {
  const lower = prompt.toLowerCase();

  if (
    lower.includes("japanese") ||
    lower.includes("translate") ||
    lower.includes("summar") ||
    lower.includes("英語") ||
    lower.includes("日本語")
  ) {
    return [
      "## English summary (demo response — not from a real model)",
      "",
      "The source material appears to discuss workplace or technical topics. Below is **sample** output only:",
      "",
      "- **Overview:** Placeholder summary of the Japanese document content.",
      "- **Key point 1:** Main argument or finding (demo).",
      "- **Key point 2:** Supporting detail or example (demo).",
      "- **Action items:** Suggested next steps for the reader.",
      "",
      "To get real translation/summary, set `AI_PROVIDER=openai` and `OPENAI_API_KEY` in Vercel, then redeploy.",
    ].join("\n");
  }

  if (category === "RESUME" || lower.includes("resume")) {
    return [
      "## Revised bullets (demo)",
      "",
      "- Led cross-functional initiative, improving delivery time by 25% (demo metric).",
      "- Partnered with stakeholders to define requirements and ship on schedule.",
      "- Mentored junior contributors and documented best practices.",
    ].join("\n");
  }

  const excerpt =
    prompt.length > 200 ? `${prompt.slice(0, 200).trim()}…` : prompt.trim();

  return [
    "## Response (demo mode)",
    "",
    "Here is sample output shaped for your prompt. It is **not** generated by OpenAI/Gemini.",
    "",
    excerpt
      ? `Your request centered on: “${excerpt}”`
      : "Your request was received.",
    "",
    "In demo mode the app returns structured placeholder text so you can test save, history, and UI flows without API keys.",
  ].join("\n");
}

export class MockAiProvider implements AiProvider {
  readonly name = "mock" as const;

  async complete(
    request: CompletionRequest,
    modelId: AiModelId = "GPT",
  ): Promise<CompletionResult> {
    const latencyMs = mockLatency(request.prompt);
    const { input, output } = mockTokens(request.prompt);
    const category = request.category ?? "GENERAL";
    const label = MODEL_LABELS[modelId];
    const systemNote = request.systemHint?.trim()
      ? `> **System:** ${request.systemHint.trim().slice(0, 120)}${request.systemHint.length > 120 ? "…" : ""}\n\n`
      : "";
    const text = `${systemNote}> **Model:** ${label}\n\n${buildMockCompletion(request.prompt, category)}`;

    return {
      text,
      modelId,
      tokenInput: input,
      tokenOutput: output,
      latencyMs,
      provider: "mock",
    };
  }

  async optimize(request: OptimizeRequest): Promise<OptimizeResult> {
    const start = Date.now();
    const rough = request.roughPrompt.trim();
    const category = request.category ?? "GENERAL";
    const instruction = request.instruction?.trim();

    const styleBlock =
      request.outputStyle === "systemUser"
        ? `## System\nYou are an expert assistant focused on ${category}.\n\n## User\n`
        : request.outputStyle === "roleBased"
          ? `## Role\nYou are an expert assistant.\n\n## Task\n`
          : request.outputStyle === "stepByStep"
            ? `Follow these steps:\n1. Understand the request.\n2. Apply constraints.\n3. Produce the output.\n\n## Task\n`
            : "";

    const optimized = [
      styleBlock || "You are an expert assistant. Follow these rules:",
      "1. Be specific about audience, tone, and output format.",
      "2. Include constraints and examples when helpful.",
      "3. Ask for clarification only if critical context is missing.",
      instruction ? `4. Optimization focus: ${instruction}` : "",
      "",
      "Task:",
      rough,
      "",
      `Context category: ${category}`,
      request.outputStyle === "jsonReady"
        ? "\nOutput: Respond with valid JSON matching the requested structure."
        : "",
    ]
      .filter(Boolean)
      .join("\n");

    const improvements = [
      "Clarity improved",
      "Structure added",
      "Output format clarified",
    ];
    if (instruction) improvements.push("Optimization goal applied");

    return {
      original: rough,
      optimized,
      improvements,
      provider: "mock",
      latencyMs: Date.now() - start + mockLatency(rough),
    };
  }

  async evaluate(input: EvaluationInput): Promise<EvaluationResult> {
    const prompt = input.prompt.trim();
    const response = (input.response ?? "").trim();
    const seed = hashSeed(prompt + response);
    const hasOutput = response.length > 0;
    const evalType = input.evaluationType ?? "ALIGNMENT";

    const clarity = Math.min(95, 58 + Math.floor(prompt.length / 30) + (seed % 12));
    const specificity = Math.min(
      92,
      50 +
        (prompt.match(/\b(must|should|format|constraint|step)\b/gi)?.length ?? 0) * 6 +
        (seed % 10),
    );
    const structure = Math.min(
      94,
      52 +
        (prompt.includes("\n") ? 18 : 6) +
        (response.includes("\n") && hasOutput ? 12 : 0) +
        (seed % 8),
    );
    const outputControl = Math.min(
      90,
      48 +
        (prompt.match(/\b(json|format|tone|length|output)\b/gi)?.length ?? 0) * 7 +
        (seed % 9),
    );
    const reusability = Math.min(88, 55 + (prompt.includes("{") ? 10 : 0) + (seed % 11));
    const reliability = hasOutput
      ? Math.min(90, 60 + Math.floor(response.length / 60) + (seed % 10))
      : Math.min(75, 45 + (seed % 15));
    const hallucinationRisk = hasOutput
      ? Math.max(8, 42 - (seed % 22) - (response.match(/\b(maybe|possibly|might)\b/gi)?.length ?? 0) * 4)
      : Math.max(10, 28 + (seed % 18));
    const productionReadiness = Math.min(
      93,
      Math.round(
        (clarity + specificity + structure + outputControl + reusability + reliability +
          (100 - hallucinationRisk)) /
          7,
      ),
    );

    let totalScore = Math.round(
      (clarity +
        specificity +
        structure +
        outputControl +
        reusability +
        reliability +
        (100 - hallucinationRisk) +
        productionReadiness) /
        8,
    );

    if (evalType === "PROMPT_QUALITY") {
      totalScore = Math.round(
        (clarity + specificity + structure + outputControl + reusability + productionReadiness) / 6,
      );
    } else if (evalType === "OUTPUT_QUALITY" && hasOutput) {
      totalScore = Math.round(
        (clarity + structure + reliability + (100 - hallucinationRisk) + productionReadiness) / 5,
      );
    } else if (evalType === "RISK_REVIEW") {
      totalScore = Math.max(0, 100 - hallucinationRisk - Math.max(0, 40 - reliability));
    }

    const rating = scoreToRating(totalScore);
    const strengths: string[] = [];
    const weaknesses: string[] = [];
    const recommendations: string[] = [];

    if (clarity >= 75) strengths.push("Clear instructions and readable phrasing");
    else weaknesses.push("Clarity could be improved with simpler, direct language");

    if (specificity >= 70) strengths.push("Specific constraints and context are present");
    else recommendations.push("Add explicit constraints, audience, and success criteria");

    if (structure >= 72) strengths.push("Logical structure supports predictable execution");
    else recommendations.push("Organize the prompt into sections (role, task, constraints, output)");

    if (outputControl >= 68) strengths.push("Output format and tone expectations are defined");
    else recommendations.push("Specify output format, length limits, and tone explicitly");

    if (reusability >= 65) strengths.push("Prompt appears reusable across similar tasks");
    else recommendations.push("Introduce variables/placeholders for reusable prompt patterns");

    if (hasOutput && reliability >= 70) strengths.push("Output alignment looks dependable for the task");
    else if (hasOutput) weaknesses.push("Output may drift from prompt intent or lack grounding");

    if (hallucinationRisk <= 25) strengths.push("Low hallucination risk indicators in the content");
    else weaknesses.push("Potential unsupported or vague claims detected");

    if (productionReadiness >= 75) strengths.push("Suitable for production workflow usage with minor polish");
    else recommendations.push("Run through Optimizer before production deployment");

    const suggestedPrompt =
      totalScore < 80
        ? [
            "You are an expert assistant.",
            "",
            "Task:",
            prompt.slice(0, 500),
            "",
            "Constraints:",
            "- Be specific and grounded in provided context",
            "- Follow the requested output format exactly",
            input.successCriteria?.trim()
              ? `- Success criteria: ${input.successCriteria.trim()}`
              : "- Avoid unsupported claims",
          ]
            .filter(Boolean)
            .join("\n")
        : undefined;

    return normalizeEvaluationResult({
      clarity,
      specificity,
      structure,
      outputControl,
      reusability,
      reliability,
      hallucinationRisk,
      productionReadiness,
      accuracy: reliability,
      usefulness: reusability,
      totalScore,
      rating,
      summary:
        "AI-assisted quality indicators (demo mode) — heuristic scores for PromptOps review workflows.",
      strengths: strengths.slice(0, 4),
      weaknesses: weaknesses.slice(0, 4),
      recommendations: recommendations.slice(0, 4),
      suggestedPrompt,
      latencyMs: mockLatency(prompt + response),
    });
  }
}
