import type { AiModelId } from "@prisma/client";
import type {
  AiProvider,
  CompletionRequest,
  CompletionResult,
  EvaluationInput,
  EvaluationResult,
  OptimizeRequest,
  OptimizeResult,
} from "./types";

const MODEL_LABELS: Record<AiModelId, string> = {
  GPT: "GPT-4o (demo)",
  GEMINI: "Gemini 2.0 (demo)",
  CLAUDE: "Claude 3.5 (demo)",
};

function hashSeed(text: string): number {
  let h = 0;
  for (let i = 0; i < text.length; i++) h = (h * 31 + text.charCodeAt(i)) | 0;
  return Math.abs(h);
}

function mockLatency(text: string): number {
  return 400 + (hashSeed(text) % 900);
}

function mockTokens(text: string): { input: number; output: number } {
  const input = Math.max(12, Math.ceil(text.length / 4));
  const output = 120 + (hashSeed(text) % 180);
  return { input, output };
}

function buildMockCompletion(prompt: string, category: string): string {
  const lower = prompt.toLowerCase();

  if (
    lower.includes("japanese") ||
    lower.includes("translate") ||
    lower.includes("summar") ||
    lower.includes("英語") ||
    lower.includes("日本語")
  ) {
    return [
      "## English summary (demo response — not from a real model)",
      "",
      "The source material appears to discuss workplace or technical topics. Below is **sample** output only:",
      "",
      "- **Overview:** Placeholder summary of the Japanese document content.",
      "- **Key point 1:** Main argument or finding (demo).",
      "- **Key point 2:** Supporting detail or example (demo).",
      "- **Action items:** Suggested next steps for the reader.",
      "",
      "To get real translation/summary, set `AI_PROVIDER=openai` and `OPENAI_API_KEY` in Vercel, then redeploy.",
    ].join("\n");
  }

  if (category === "RESUME" || lower.includes("resume")) {
    return [
      "## Revised bullets (demo)",
      "",
      "- Led cross-functional initiative, improving delivery time by 25% (demo metric).",
      "- Partnered with stakeholders to define requirements and ship on schedule.",
      "- Mentored junior contributors and documented best practices.",
    ].join("\n");
  }

  const excerpt =
    prompt.length > 200 ? `${prompt.slice(0, 200).trim()}…` : prompt.trim();

  return [
    "## Response (demo mode)",
    "",
    "Here is sample output shaped for your prompt. It is **not** generated by OpenAI/Gemini.",
    "",
    excerpt
      ? `Your request centered on: “${excerpt}”`
      : "Your request was received.",
    "",
    "In demo mode the app returns structured placeholder text so you can test save, history, and UI flows without API keys.",
  ].join("\n");
}

export class MockAiProvider implements AiProvider {
  readonly name = "mock" as const;

  async complete(
    request: CompletionRequest,
    modelId: AiModelId = "GPT",
  ): Promise<CompletionResult> {
    const latencyMs = mockLatency(request.prompt);
    const { input, output } = mockTokens(request.prompt);
    const category = request.category ?? "GENERAL";
    const text = buildMockCompletion(request.prompt, category);

    return {
      text,
      modelId,
      tokenInput: input,
      tokenOutput: output,
      latencyMs,
      provider: "mock",
    };
  }

  async optimize(request: OptimizeRequest): Promise<OptimizeResult> {
    const rough = request.roughPrompt.trim();
    const optimized = [
      "You are an expert assistant. Follow these rules:",
      "1. Be specific about audience, tone, and output format.",
      "2. Include constraints and examples when helpful.",
      "3. Ask for clarification only if critical context is missing.",
      "",
      "Task:",
      rough,
      "",
      `Context category: ${request.category ?? "GENERAL"}`,
    ].join("\n");

    return {
      original: rough,
      optimized,
      improvements: [
        "Added role and behavior framing",
        "Structured task vs. meta-instructions",
        "Included category context",
      ],
      provider: "mock",
    };
  }

  async evaluate(input: EvaluationInput): Promise<EvaluationResult> {
    const len = input.response.length;
    const clarity = Math.min(95, 60 + Math.floor(len / 40));
    const structure = Math.min(92, 55 + (input.response.includes("\n") ? 25 : 10));
    const accuracy = 70 + (hashSeed(input.prompt) % 20);
    const usefulness = Math.min(90, 50 + Math.floor(len / 50));
    const hallucinationRisk = Math.max(5, 35 - (hashSeed(input.response) % 25));
    const totalScore = Math.round(
      (clarity + structure + accuracy + usefulness + (100 - hallucinationRisk)) / 5,
    );

    return {
      clarity,
      structure,
      accuracy,
      usefulness,
      hallucinationRisk,
      totalScore,
      summary: "Demo evaluation — heuristic scores for UI testing.",
    };
  }
}
